"""empty message

Revision ID: 503a165beda4
Revises: 83855a5ff240
Create Date: 2020-09-18 17:37:09.027056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503a165beda4'
down_revision = '83855a5ff240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist_genres', sa.Column('genre_name', sa.String(length=128), nullable=False))
    op.drop_column('artist_genres', 'name')
    op.add_column('venue__genre', sa.Column('genre_name', sa.String(length=128), nullable=False))
    op.drop_column('venue__genre', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue__genre', sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_column('venue__genre', 'genre_name')
    op.add_column('artist_genres', sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_column('artist_genres', 'genre_name')
    # ### end Alembic commands ###
