"""empty message

Revision ID: e83278457fa4
Revises: 131712123fc0
Create Date: 2020-09-18 23:34:39.995597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e83278457fa4'
down_revision = '131712123fc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('show_date', sa.DateTime(), nullable=False))
    op.drop_column('shows', 'show_Date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('show_Date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('shows', 'show_date')
    # ### end Alembic commands ###
